#  Template python-build

#  This template allows you to validate your python code.
#  The workflow allows running tests on the default branch.

image: python:3.8

pipelines:
  default:
    - step:
        name: Test
        caches:
          - pip
        script:
          - pip install -r backend/requirements.txt
          - cd backend
          - python -m unittest
