version: "3.8"

services:
  mysql:
    image: mysql
    ports:
      - 3307:3306
    environment:
      MYSQL_ROOT_PASSWORD: p@ssw0rd1 # Change this to a unique, strong password for added security.
      MYSQL_DATABASE: db
    volumes:
      - mysql-data:/var/lib/mysql

  backend:
    build: ./backend
    ports:
      - 8080:8080
    volumes:
      - ./backend:/app
    depends_on:
      - "mysql"
    environment:
      MYSQL_HOST: mysql
      MYSQL_USER: root
      MYSQL_PASSWORD: p@ssw0rd1 # Change this to a unique, strong password for added security.
      MYSQL_DB: db
      JWT_SECRET_KEY: s3cr3tk3y # Change this to a unique, strong key for added security.

  frontend:
    build: ./frontend
    ports:
      - 80:80
    volumes:
      - ./frontend:/app

volumes:
  mysql-data:
